(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/diy_components/bargain"],{2170:function(t,e,n){"use strict";n.r(e);var a=n("4c68"),r=n.n(a);for(var i in a)"default"!==i&&function(t){n.d(e,t,function(){return a[t]})}(i);e["default"]=r.a},"31d9":function(t,e,n){"use strict";var a=n("b310"),r=n.n(a);r.a},3722:function(t,e,n){"use strict";var a,r=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"b",function(){return r}),n.d(e,"c",function(){return i}),n.d(e,"a",function(){return a})},"4c68":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a={name:"bargain",props:{bargain:{type:Object,value:"bargain"},list2:{},bartime:[]},data:function(){return{test:[],siteroot:"",$imgurl:this.$imgurl}},onLoad:function(){},created:function(){this.siteroot=this.$host,this.gettime()},methods:{redirectto:function(t){var e=t.currentTarget.dataset.link,n=t.currentTarget.dataset.linktype;this._redirectto(e,n)},daojs:function(){for(var t=this,e=[],n=t.list2,a=0;a<n.length;a++){var r=new Date,i=r.getTime();if(0==n[a]["sale_time"]&&0==n[a]["sale_end_time"]);else if(1e3*n[a]["sale_time"]>i)n[a]["t_flag"]=1;else if(1e3*n[a]["sale_end_time"]<i)n[a]["t_flag"]=2;else if(n[a]["sale_end_time"]<=0)n[a]["endtime"]=0;else{var o,l,s,f,u=1e3*parseInt(n[a]["sale_end_time"]),c=u-i;if(c>=0&&(o=Math.floor(c/1e3/60/60/24),l=Math.floor(c/1e3/60/60%24)<10?"0"+Math.floor(c/1e3/60/60%24):Math.floor(c/1e3/60/60%24),s=Math.floor(c/1e3/60%60)<10?"0"+Math.floor(c/1e3/60%60):Math.floor(c/1e3/60%60),f=Math.floor(c/1e3%60)<10?"0"+Math.floor(c/1e3%60):Math.floor(c/1e3%60)),o>0){n[a]["endtime"]=o+"天"+l+":"+s+":"+f;var d=o+"天"+l+":"+s+":"+f}else{n[a]["endtime"]=l+":"+s+":"+f;d=l+":"+s+":"+f}e[a]=d,t.test=e}}},gettime:function(){var t=this;setInterval(function(){t.daojs()},1e3)}}};e.default=a},b310:function(t,e,n){},d4cb:function(t,e,n){"use strict";n.r(e);var a=n("3722"),r=n("2170");for(var i in r)"default"!==i&&function(t){n.d(e,t,function(){return r[t]})}(i);n("31d9");var o,l=n("f0c5"),s=Object(l["a"])(r["default"],a["b"],a["c"],!1,null,null,null,!1,a["a"],o);e["default"]=s.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/diy_components/bargain-create-component',
    {
        'components/diy_components/bargain-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("d4cb"))
        })
    },
    [['components/diy_components/bargain-create-component']]
]);
