<?php
return [
  [
    'title' => '拼多多',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/pinduoduo',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 0,
    'childs' => [
      [
        'title' => '常用菜单',
        'icon' => 'aicon ai-shouye',
        'module' => 'system',
        'url' => 'system/pingduoduo/infos',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '个人信息设置',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/info',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
          [
            'title' => '基础信息',
            'icon' => 'aicon ai-doubleleft',
            'module' => 'system',
            'url' => 'system/pinduoduo/infos',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '数据统计',
            'icon' => 'aicon ai-shouyeshouye',
            'module' => 'system',
            'url' => 'system/pinduoduo/reports',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '错误日志',
            'icon' => 'aicon ai-cha',
            'module' => 'system',
            'url' => 'system/pinduoduo/errors',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '商户中心',
            'icon' => 'fa fa-flag-o',
            'module' => 'system',
            'url' => 'system/pinduoduo/clients',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '订单管理',
        'icon' => 'aicon ai-shujukuguanli',
        'module' => 'system',
        'url' => 'system/pinduoduo/orders',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '订单列表',
            'icon' => 'aicon ai-shujukuguanli',
            'module' => 'system',
            'url' => 'system/pinduoduo/orders',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '售后订单',
            'icon' => 'aicon ai-chajianguanli',
            'module' => 'system',
            'url' => 'system/pinduoduo/after_sales',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '农产品订单',
            'icon' => 'aicon ai-shujukuguanli',
            'module' => 'system',
            'url' => 'system/pinduoduo/orders_ncp',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '店铺管理',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'system/pinduoduo/goods',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '商品列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'system',
            'url' => 'system/pinduoduo/goods',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '添加商品',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/goods_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '店铺列表',
            'icon' => 'aicon ai-mokuaiguanli1',
            'module' => 'system',
            'url' => 'system/pinduoduo/stores',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '添加店铺',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/stores_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '帐号管理',
        'icon' => 'aicon ai-huiyuanliebiao',
        'module' => 'system',
        'url' => 'system/pinduoduo/users',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '帐号列表',
            'icon' => 'aicon ai-huiyuanliebiao',
            'module' => 'system',
            'url' => 'system/pinduoduo/users',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '公共帐号',
            'icon' => 'aicon ai-gongneng',
            'module' => 'system',
            'url' => 'system/pinduoduo/users_public',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '添加帐号',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/users_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '添加QQ号',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/qq_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '一键导入',
            'icon' => 'aicon ai-chu1',
            'module' => 'system',
            'url' => 'system/pinduoduo/onekey',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '员工管理',
        'icon' => 'aicon ai-huiyuandengji',
        'module' => 'system',
        'url' => 'system/pinduoduo/staffs',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '员工列表',
            'icon' => 'aicon ai-huiyuandengji',
            'module' => 'system',
            'url' => 'system/pinduoduo/staffs',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '添加员工',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/staffs_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '提现管理',
        'icon' => 'typcn typcn-anchor',
        'module' => 'system',
        'url' => 'system/pinduoduo/cash',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '申请提现',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/pinduoduo/cash_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '结算管理',
            'icon' => 'aicon ai-chajianguanli',
            'module' => 'system',
            'url' => 'system/pinduoduo/settlement',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '结算确认',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/settlement_status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '结算取消',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/settlement_cancel',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '我的结算',
            'icon' => 'aicon ai-xitongrizhi-tiaoshi',
            'module' => 'system',
            'url' => 'system/pinduoduo/my_settlement',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '结算取消',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/my_settlement_cancel',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '我的代收银行',
            'icon' => 'fa fa-home',
            'module' => 'system',
            'url' => 'system/pinduoduo/bank',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '修改银行名称',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/bank_retitle',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '修改收款人姓名',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/bank_rename',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '修改收款账号',
                'icon' => 'aicon ai-jinzhi',
                'module' => 'system',
                'url' => 'system/pinduoduo/bank_readdress',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '添加代收银行',
            'icon' => 'aicon ai-tianjia',
            'module' => 'system',
            'url' => 'system/pinduoduo/bank_add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '绑定Google验证器',
            'icon' => 'typcn typcn-key-outline',
            'module' => 'system',
            'url' => 'system/pinduoduo/google_bind',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '自动任务',
        'icon' => 'typcn typcn-arrow-repeat',
        'module' => 'system',
        'url' => 'system/pinduoduo/OnPayOneMinute',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '一分钟订单支付',
            'icon' => 'typcn typcn-arrow-repeat',
            'module' => 'system',
            'url' => 'system/pinduoduo/OnPayOneMinute',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '五分钟订单支付',
            'icon' => 'typcn typcn-arrow-repeat',
            'module' => 'system',
            'url' => 'system/pinduoduo/OnPayFiveMinute',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '确认收货',
            'icon' => 'typcn typcn-arrow-repeat',
            'module' => 'system',
            'url' => 'system/pinduoduo/Received',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '统计',
            'icon' => 'typcn typcn-arrow-repeat',
            'module' => 'system',
            'url' => 'system/pinduoduo/Statistic',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
