(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/bsfooter/bsfooter"],{"179c":function(n,e,t){},3084:function(n,e,t){"use strict";t.r(e);var a=t("6154"),o=t("432d");for(var r in o)"default"!==r&&function(n){t.d(e,n,function(){return o[n]})}(r);t("f12e");var i,u=t("f0c5"),c=Object(u["a"])(o["default"],a["b"],a["c"],!1,null,null,null,!1,a["a"],i);e["default"]=c.exports},"432d":function(n,e,t){"use strict";t.r(e);var a=t("ae9e"),o=t.n(a);for(var r in a)"default"!==r&&function(n){t.d(e,n,function(){return a[n]})}(r);e["default"]=o.a},6154:function(n,e,t){"use strict";var a,o=function(){var n=this,e=n.$createElement;n._self._c},r=[];t.d(e,"b",function(){return o}),t.d(e,"c",function(){return r}),t.d(e,"a",function(){return a})},ae9e:function(n,e,t){"use strict";(function(n){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var t={props:["baseinfo"],data:function(){return{isIphoneX:"",manager_rule:[]}},created:function(){var e=this;this.manager_rule=n.getStorageSync("manager_rule"),n.getSystemInfo({success:function(n){var t=n,a=t.model;-1!=a.search("iPhone X")&&(e.isIphoneX=!0)}})},methods:{toIndex:function(){this.active_on=1,n.reLaunch({url:"/pagesBackStage/index/index"})},proManage:function(){this.manager_rule.indexOf(1)>-1?n.navigateTo({url:"/pagesBackStage/pro_manage/pro_manage"}):n.showToast({title:"您暂无权限管理该栏目！",duration:1500,icon:"none"})},orderList:function(){this.manager_rule.indexOf(2)>-1?n.navigateTo({url:"/pagesBackStage/order_list/order_list"}):n.showToast({title:"您暂无权限管理该栏目！",duration:1500,icon:"none"})},contentManage:function(){this.manager_rule.indexOf(3)>-1?n.navigateTo({url:"/pagesBackStage/content_manage/content_manage"}):n.showToast({title:"您暂无权限管理该栏目！",duration:1500,icon:"none"})},setting:function(){this.manager_rule.indexOf(4)>-1?n.navigateTo({url:"/pagesBackStage/setting/setting"}):n.showToast({title:"您暂无权限管理该栏目！",duration:1500,icon:"none"})}}};e.default=t}).call(this,t("5486")["default"])},f12e:function(n,e,t){"use strict";var a=t("179c"),o=t.n(a);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/bsfooter/bsfooter-create-component',
    {
        'components/bsfooter/bsfooter-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("3084"))
        })
    },
    [['components/bsfooter/bsfooter-create-component']]
]);
